version: '3'
services:
    gateway:
        image: nginx:mainline-alpine-slim
        container_name: gateway
        restart: unless-stopped
        ports:
            - '3000:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - core-network
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    turbo:
        container_name: app
        restart: unless-stopped
        build:
          context: .
          dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - core-network
        volumes:
            - .:/app
networks:
    core-network:
        driver: bridge
