version: '3'
services:
    gateway:
        image: nginx:mainline-alpine-slim
        container_name: gateway
        restart: unless-stopped
        ports:
            - '3000:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - core-network
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    turbo:
        container_name: app
        restart: unless-stopped
        build:
          context: .
          dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - core-network
        ports:
            - '5555:5555'
        volumes:
            - .:/app
            - .pnpm:/root/.local/share/pnpm/store
    db:
        container_name: db
        restart: unless-stopped
        image: 'postgres:alpine3.18'
        environment:
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'root'
        volumes:
            - ./config/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - core-network
networks:
    core-network:
        driver: bridge
