import { organization } from 'ui/config'

export const metadata = {
  title: `${organization.name}`,
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
      <main className="flex min-h-screen flex-col items-center gap-4 p-24">
        <h1>
          Storefornt Page
        </h1>
      </main>
    </>
  )
}
