name: Jest Unit Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      pnpm-version: 8.8.0
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      DATABASE_URL: "postgresql://root:root@db:5432"

    services:
      postgres:
        image: 'postgres'
        env:
          POSTGRES_PASSWORD: 'secret'
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize Database
        run: PGPASSWORD=secret psql -U postgres -h 127.0.0.1 -p ${{ job.services.postgres.ports[5432] }} -f ./config/postgresql/init.sql