name: Jest Unit Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      pnpm-version: 8.8.0
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    services:
      postgres:
        image: 'postgres'
        env:
          POSTGRES_PASSWORD: 'password'
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize Database
        run: PGPASSWORD=password psql -U postgres -h 127.0.0.1 -p ${{ job.services.postgres.ports[5432] }} -f ./config/postgresql/init.sql

      - name: Cache dependencies
        uses: actions/cache@v3
        id: dependencies-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-turborepo-${{ hashFiles('**/pnpm-lock.yaml') }}-tests

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - name: Install Dependencies
        if: steps.dependencies-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
      
      - name: Run Tests
        run: pnpm test