import React from 'react'

export const metadata = {
  title: `${organization.name} | About Us`,
  description: 'Generated by create next app',
}

export default function page() {
  return (
    <div>About Page</div>
  )
}
